### ISSUE TITLE
Upgrade to dotnetcore LTS

### ISSUE THREAD

**Issue by jonedavis** [TwilioDevEd/airtng-csharp-dotnet-core#89]
Update to dotnetcore lts 3.1

```
4967:AirTNG.Web jdavis$ dotnet ef database update
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.5' was not found.
  - The following frameworks were found:
      3.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

**Comment by po5i** [comment]
It was updated on the PR: [here](https://github.com/TwilioDevEd/airtng-csharp-dotnet-core/pull/84/files#diff-fd78dcaadfe8183dae6ce55f6910440aR19), [here](https://github.com/TwilioDevEd/airtng-csharp-dotnet-core/pull/84/files#diff-c5e9e2c3fd04d0fe2f17440723cbb631R4), and [here](https://github.com/TwilioDevEd/airtng-csharp-dotnet-core/pull/84/files#diff-9bb991e4cb88951f2a3996da56e967bdR46) you can see some examples. Am I missing something?

**Comment by jonedavis** [comment]
This is my fault :) Closing
